Datasets comparison


In [1]:
import torch
from torchtext import data, datasets

Version 0.6.0


In [2]:
TEXT = data.Field(lower=True, include_lengths=True, batch_first=True)
# LABEL = data.Field(sequential=False)
LABEL = data.LabelField(dtype=torch.float)
train_data, test_data = datasets.IMDB.splits(TEXT, LABEL)
print(f"Training examples: {len(train_data)}")
print(f"Testing examples:  {len(test_data)}")

vocab_size = 20000
TEXT.build_vocab(train_data, max_size=vocab_size - 2)  # exclude <UNK> and <PAD>
LABEL.build_vocab(train_data)

Training examples: 25000
Testing examples:  25000


In [3]:
print(train_data.fields)
print(train_data.examples[0].text)
print(train_data.examples[0].label)
print(len(train_data.examples))
print(train_data.examples[-1].text)
print(train_data.examples[-1].label)

{'text': <torchtext.data.field.Field object at 0x1769786d0>, 'label': <torchtext.data.field.LabelField object at 0x175fbd4d0>}
['for', 'a', 'movie', 'that', 'gets', 'no', 'respect', 'there', 'sure', 'are', 'a', 'lot', 'of', 'memorable', 'quotes', 'listed', 'for', 'this', 'gem.', 'imagine', 'a', 'movie', 'where', 'joe', 'piscopo', 'is', 'actually', 'funny!', 'maureen', 'stapleton', 'is', 'a', 'scene', 'stealer.', 'the', 'moroni', 'character', 'is', 'an', 'absolute', 'scream.', 'watch', 'for', 'alan', '"the', 'skipper"', 'hale', 'jr.', 'as', 'a', 'police', 'sgt.']
pos
25000
['not', 'that', 'i', 'dislike', 'childrens', 'movies,', 'but', 'this', 'was', 'a', 'tearjerker', 'with', 'few', 'redeeming', 'qualities.', 'm.j.', 'fox', 'was', 'the', 'perfect', 'voice', 'for', 'stuart', 'and', 'the', 'rest', 'of', 'the', 'talent', 'was', 'wasted.', 'hugh', 'laurie', 'can', 'be', 'amazingly', 'funny,', 'but', 'is', 'not', 'given', 'the', 'chance', 'in', 'this', 'movie.', 'it´s', 'sugar-coated', 'suga

In [4]:
sorted([len(example.text) for example in train_data.examples])[-1]

2470

In [5]:
print(train_data)

In [6]:
print(sorted(TEXT.vocab.itos))

['!', '!!', '!!!', '!<br', '"', '"1"', '"10', '"a', '"acting"', '"action"', '"actors"', '"alien', '"all', '"american', '"an', '"and', '"animal', '"are', '"art"', '"as', '"at', '"attack', '"b"', '"baby', '"back', '"bad', '"bad"', '"basic', '"batman', '"be', '"before', '"bend', '"best', '"beyond', '"big', '"black', '"blood', '"blue', '"braveheart"', '"but', '"by', '"can', '"castle', '"cinderella"', '"citizen', '"city', '"come', '"comedy"', '"cool', '"cool"', '"dan', '"dark', '"dead', '"death', '"der', '"die', '"dirty', '"do', '"doctor', '"dog', '"don\'t', '"down', '"dr.', '"dressed', '"el', '"evil', '"f"', '"family', '"family"', '"fight', '"film"', '"final', '"first', '"for', '"friday', '"from', '"full', '"funny"', '"get', '"go', '"going', '"gone', '"good', '"good"', '"great', '"great"', '"hamlet"', '"happy', '"he', '"heaven', '"hero"', '"hey', '"hey,', '"high', '"hollywood', '"home', '"hood', '"horror"', '"hot', '"house', '"how', '"i', '"i\'ll', '"i\'m', '"if', '"in', '"inspector', '"is

In [7]:
print(TEXT.vocab.itos[-10:])

['affairs,', 'affectionate', 'afforded', 'airport,', 'albert.', 'alcoholic,', "alex's", 'all),', 'all-american', 'allen.']


In [8]:
print(len(TEXT.vocab))

20000


In [9]:
TEXT.dtypes

{torch.float32: float,
 torch.float64: float,
 torch.float16: float,
 torch.uint8: int,
 torch.int8: int,
 torch.int16: int,
 torch.int32: int,
 torch.int64: int}

In [10]:
batch_size = 32

train_iter, test_iter = data.BucketIterator.splits(
    (train_data, test_data), batch_size=batch_size
)

In [11]:
train_sample = next(iter(train_iter))
print(train_sample.text)
print([text.size() for text in train_sample.text])
print(train_sample.label)
print(train_sample.label.size())

(tensor([[  78,   89,   36,  ...,    1,    1,    1],
        [   2,  358,  894,  ...,    1,    1,    1],
        [ 310,   12,   14,  ...,    1,    1,    1],
        ...,
        [   9,  302, 1041,  ...,    1,    1,    1],
        [   2,   82,  103,  ...,    1,    1,    1],
        [   9,   26,  359,  ...,    1,    1,    1]]), tensor([ 432,  116,   57,  157,   94,  184,  316, 1001,  747,  154,  117,  104,
         367,  382,  212,  272,  231,  148,  256,  401,  155,  132,  138,  128,
          82,  417,  164,  440,  124,  153,  110,  109]))
[torch.Size([32, 1001]), torch.Size([32])]
tensor([1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
        0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.])
torch.Size([32])


In [15]:
print(train_sample.text[0])
print(train_sample.text[0].size())

tensor([[  78,   89,   36,  ...,    1,    1,    1],
        [   2,  358,  894,  ...,    1,    1,    1],
        [ 310,   12,   14,  ...,    1,    1,    1],
        ...,
        [   9,  302, 1041,  ...,    1,    1,    1],
        [   2,   82,  103,  ...,    1,    1,    1],
        [   9,   26,  359,  ...,    1,    1,    1]])
torch.Size([32, 1001])


In [12]:
print(len([sample.text[0].size() for sample in list(train_iter)]))

782


In [13]:
list(train_iter)

[
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x837]', '[torch.LongTensor of size 32]')
 	[.label]:[torch.FloatTensor of size 32],
 
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x855]', '[torch.LongTensor of size 32]')
 	[.label]:[torch.FloatTensor of size 32],
 
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x996]', '[torch.LongTensor of size 32]')
 	[.label]:[torch.FloatTensor of size 32],
 
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x1005]', '[torch.LongTensor of size 32]')
 	[.label]:[torch.FloatTensor of size 32],
 
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x614]', '[torch.LongTensor of size 32]')
 	[.label]:[torch.FloatTensor of size 32],
 
 [torchtext.data.batch.Batch of size 32 from IMDB]
 	[.text]:('[torch.LongTensor of size 32x961]', '[torch.LongT